### ISSUE TITLE
'Not Found' Error When Calling GetJobAsync

### ISSUE THREAD

**Issue by bmasephol** [Bassman2/JenkinsWebApi#12]
I'm running into a Not Found error being thrown when calling GetJobAsync.  I've debugged locally to track it back to the Jenkins type org.jenkinsci.plugins.workflow.job.WorkflowJob not mapping to class JenkinsOrgJenkinsciPluginsWorkflowJobWorkflowJob through the code.  

I think the issue is in class Jenkins at line 41 where it populates the buildTypes array.  I believe the issue is that the typeof(JenkinsModelAbstractBuild) should actually be typeof(JenkinsModelRun).  I've made this change locally and it seems to resolve the issue I was having.

I'll be prepping a pull request with that change included as well.

**Comment by Bassman2** [comment]
Fixed
