### ISSUE TITLE
Jenkins Job Result has wrong return type

### ISSUE THREAD

**Issue by PulsarFX** [Bassman2/JenkinsWebApi#9]
Currently `JenkinsModelRun` has the following property:
```csharp
[XmlElement("result")]
public JenkinsTasksTestTestResult Result { get; set; }
```

At least on my build definitions, `result` shows up in the API as `anyType`
```xml
<xsd:element name="result" type="xsd:anyType" minOccurs="0"/>
```

I get a XmlNode array back from this, if I change the type to `object`
```csharp
[XmlElement("result")]
public object Result { get; set; }
```

Is `Result` actually populated with `JenkinsTasksTestTestResult ` in your cases?

For example another `anyType`
```xml
<xsd:sequence>
  <xsd:element name="action" type="xsd:anyType" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
```

This is mapped to `object`, which matches the schema:
```csharp
[XmlElement("action")]
public object[] Actions { get; set; }
```

**Comment by Bassman2** [comment]
That's right the schema says xsd: anyType. 
And an object [] implementation would be logical. An implementation like in JenkinsModelComputer only makes sense if really different classes are passed. 
In my tests, however, only JenkinsTasksTestTestResult was passed at this point. 
Therefore an implementation with object [] makes everything unnecessarily complicated. 
If you saw a different return class, please inform me and describe how you got it.

**Comment by PulsarFX** [comment]
I get an `XmlNode[]` with 1 entry with the status of the build as TEXT
![grafik](https://user-images.githubusercontent.com/4960210/93349681-1442ca80-f838-11ea-9e2b-40a02af75990.png)

My job has 3 steps: windows batch, powershell, windows batch. 
For linux build it is one step "execute shell"

**Comment by Bassman2** [comment]
I need the value of the OuterXml property of the XmlNode class.

**Comment by PulsarFX** [comment]
In XML this looks like `<result>SUCCESS</result>`
VS shows:
![grafik](https://user-images.githubusercontent.com/4960210/93568574-a958d700-f990-11ea-8636-a257985356ca.png)

**Comment by PulsarFX** [comment]
The whole XML is
```xml
<freeStyleBuild _class='hudson.model.FreeStyleBuild'>
    <action _class='hudson.model.ParametersAction'>
        <parameter _class='hudson.model.FileParameterValue'>
            <name>codearchive.zip</name>
        </parameter>
        <parameter _class='hudson.model.FileParameterValue'>
            <name>librariesRoot.zip</name>
        </parameter>
        <parameter _class='hudson.model.FileParameterValue'>
            <name>cmakescript.bat</name>
        </parameter>
        <parameter _class='hudson.model.FileParameterValue'>
            <name>modelCoreSrc.zip</name>
        </parameter>
    </action>
    <action _class='hudson.model.CauseAction'>
        <cause _class='hudson.model.Cause$UserIdCause'>
            <shortDescription>Started by user builduser</shortDescription>
            <userId>builduser</userId>
            <userName>builduser</userName>
        </cause>
    </action>
    <action></action>
    <action></action>
    <building>false</building>
    <displayName>#189</displayName>
    <duration>188738</duration>
    <estimatedDuration>181109</estimatedDuration>
    <fullDisplayName>build_win #189</fullDisplayName>
    <id>189</id>
    <keepLog>false</keepLog>
    <number>189</number>
    <queueId>100</queueId>
    <result>SUCCESS</result>
    <timestamp>1600411853680</timestamp>
    <url>...:8080/job/build_win/189/</url>
    <builtOn>winlokal</builtOn>
    <changeSet _class='hudson.scm.EmptyChangeLogSet'></changeSet>
</freeStyleBuild>
```

**Comment by bmasephol** [comment]
I'm finding the same issue as well.  I'm seeing a <result>SUCCESS</result> node show up in the org.jenkinsci.plugins.workflow.job.WorkflowRun implementation.  Maybe it is a bad schema definition by the Jenkins team to define it as anyType.

![image](https://user-images.githubusercontent.com/12200343/95767543-801f2400-0c7a-11eb-93dc-5915239cc805.png)

![image](https://user-images.githubusercontent.com/12200343/95767622-a2b13d00-0c7a-11eb-97cb-3a7cf815fa52.png)

I also took a look at what it shows up as for a failed build.

![image](https://user-images.githubusercontent.com/12200343/95767758-d5f3cc00-0c7a-11eb-9172-b98dfe6a6c5b.png)

I see the mapping of anyType to a specific class, but it looks like maybe it would be better left as a string value.

![image](https://user-images.githubusercontent.com/12200343/95767852-020f4d00-0c7b-11eb-9b4d-0eaa05bfcc7f.png)

But maybe it is just a specific implementation for some and doesn't apply to all.  I'm not super familiar with all of the different parts of Jenkins.

**Comment by Bassman2** [comment]
Fixed
